### PR TITLE
Replace satori/go.uuid with google/uuid

### LINKED ISSUE #660: go.uuid import is broken
After merging of #659 , it turns out that satori/go.uuid is broken and doesn't work as intended with a go-module. As at least one other fork of it, gofrs/uuid, removed go.mod support, I propose go.uuid is replaced with `google/uuid`.

In the meantime, a workaround can be

```
	github.com/satori/go.uuid v1.2.1-0.20181028125025-b2ce2384e17b // indirect
```

in onet/go.mod.

### PR DESCRIPTION
**Pull request by gnarula**
Replaces the uuid dependency to google/uuid which is actively maintained and uses go.mod

Closes #660

### CODE REVIEW

**Review by ineiti — CHANGES_REQUESTED** [review]
LGTM - one question remains:

- is it in fact OK to replace the uuid-library, as the uuid.UUID is used in some of the types? -> do we break the API with that change?

**Comment by gnarula** [comment]
I don't think `uuid.UUID` is exposed directly to the users - the end users would always deal with types like `ServerIdentityID` and the methods defined on it.

Under the hood, both dependencies share the same representation:
https://github.com/satori/go.uuid/blob/b2ce2384e17bbe0c6d34077efa39dbab3e09123b/uuid.go#L37 and https://github.com/google/uuid/blob/0e4e31197428a347842d152773b4cace4645ca25/uuid.go#L19

**Comment by ineiti** [comment]
Did you try to compile `dedis/cothority` using these changes?

**Review by ineiti — APPROVED** [review]

**Comment by ineiti** [comment]
So I can compile `dedis/cothority` with these changes - so it should be OK...

**Comment by gnarula** [comment]
@ineiti it builds fine but I'm getting some test failures on `dedis/cothority` which I'm looking into

>>> router.go:215 (network.(*Router).Start.func1) - receiving server identity from "" failed: Error while receiving ServerIdentity during negotiation receiving: [::1]:64212 sends too big packet: 1195725856>10485760

**Comment by ineiti** [comment]
> Edit: Nvm, getting it irrespective of this change :/

Which test is that?

**Comment by gnarula** [comment]
> > Edit: Nvm, getting it irrespective of this change :/
> 
> Which test is that?

`blscosi.TestClient_SignatureRequest`, `blscosi.TestService_SignatureRequest` `byzcoin.TestClient_NoPhantomSkipchain`,`contracts.TestDeferred_ExpireBlockIndex`, `calypso.TestClient_Authorize`

**Comment by ineiti** [comment]
> `blscosi.TestClient_SignatureRequest`, `blscosi.TestService_SignatureRequest` `byzcoin.TestClient_NoPhantomSkipchain`,`contracts.TestDeferred_ExpireBlockIndex`, `calypso.TestClient_Authorize`

Here the error disappears if I run them individually - can you confirm that? Else we'll need to open an issue for this...

**Comment by gnarula** [comment]
=

> > `blscosi.TestClient_SignatureRequest`, `blscosi.TestService_SignatureRequest` `byzcoin.TestClient_NoPhantomSkipchain`,`contracts.TestDeferred_ExpireBlockIndex`, `calypso.TestClient_Authorize`
> 
> Here the error disappears if I run them individually - can you confirm that? Else we'll need to open an issue for this...

Same here, errors disappear if I run the tests individually

**Comment by ineiti** [comment]
So I think this should go in.

**Pull request merged**
