### PR TITLE
fixed toml parsing

### LINKED ISSUE #152: Simulation silently hangs on valid toml
If all lines are of the form
```
key1=val1
```
the simulation hangs silently. 
To fix, the last line must be of the form
```
keyY=valY

keyZ
valZ
```

### PR DESCRIPTION
**Pull request by christophebertrand**
closes #152

### CODE REVIEW

**Comment by nikkolasg** [comment]
A test would be good :)

**Comment by ineiti** [comment]
Thinking out loud: shouldn't it fail if we don't have the tail with

```
key1[, key2]
value1[, value2]
```
? Usually that tail indicates the experiments we want to run. So if the tail is missing, it's like it's just 1 experiment. Isn't this confusing?

**Comment by nikkolasg** [comment]
@ineiti I'm ok with **not** failing if there is no "csv" part since one can run one experiment...

**Comment by nikkolasg** [comment]
LGTM for me.

**Pull request merged**
