### PR TITLE
Check decoding in go-routine

### PR DESCRIPTION
**Pull request by ineiti**
To avoid too many requests on nodes, decode the correct replies already in the
go-routine. This avoids the channel filling up with potential correct
data that will only be checked in the consumer-loop.

This also simplifies the number of channels used.

Replaces #570

### CODE REVIEW

**Comment by ineiti** [comment]
> Should't the first `select case` priorize the `case <- done` statement? With something like:

As far as I understand go, there is no such thing as _priorities_ in a `select` statement - they're chosen at random, see here:

https://yourbasic.org/golang/select-explained/

**Comment by nkcr** [comment]
> As far as I understand go, there is no such thing as _priorities_ in a `select` statement - they're chosen at random

Yes, exactly. Except for the default case, which is executed only when no other cases can be run. This is why in my example, for the first select, I kept only the `case <-done:` and moved the rest in the default case. This ensures that we always check for the `done` Chanel.

**Comment by ineiti** [comment]
OK - got it. Thanks for explaining ;) I also put the `select` in a separate variable, else the indention gets a bit out of control...

**Comment by ineiti** [comment]
And btw: I checked on play.golang.org, and a closed channel does not have priority over other channels that have data available. It is random also including closed channels.

**Comment by nkcr** [comment]
Do you want to wait on Galylor's review, or should I merge it?

**Comment by ineiti** [comment]
It was an answer to #570, so if you know how to reproduce the error that got @kc1212 to write #570, then please look if this PR fixes it. I prefer this over #570, so if you go ahead and merge it, you should also close #570.

**Pull request merged**
